require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DatesController do

  # This should return the minimal set of attributes required to create a valid
  # Date. As you add validations to Date, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dates as @dates" do
      date = Date.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dates).should eq([date])
    end
  end

  describe "GET show" do
    it "assigns the requested date as @date" do
      date = Date.create! valid_attributes
      get :show, {:id => date.to_param}, valid_session
      assigns(:date).should eq(date)
    end
  end

  describe "GET new" do
    it "assigns a new date as @date" do
      get :new, {}, valid_session
      assigns(:date).should be_a_new(Date)
    end
  end

  describe "GET edit" do
    it "assigns the requested date as @date" do
      date = Date.create! valid_attributes
      get :edit, {:id => date.to_param}, valid_session
      assigns(:date).should eq(date)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Date" do
        expect {
          post :create, {:date => valid_attributes}, valid_session
        }.to change(Date, :count).by(1)
      end

      it "assigns a newly created date as @date" do
        post :create, {:date => valid_attributes}, valid_session
        assigns(:date).should be_a(Date)
        assigns(:date).should be_persisted
      end

      it "redirects to the created date" do
        post :create, {:date => valid_attributes}, valid_session
        response.should redirect_to(Date.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved date as @date" do
        # Trigger the behavior that occurs when invalid params are submitted
        Date.any_instance.stub(:save).and_return(false)
        post :create, {:date => {  }}, valid_session
        assigns(:date).should be_a_new(Date)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Date.any_instance.stub(:save).and_return(false)
        post :create, {:date => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested date" do
        date = Date.create! valid_attributes
        # Assuming there are no other dates in the database, this
        # specifies that the Date created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Date.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => date.to_param, :date => { "these" => "params" }}, valid_session
      end

      it "assigns the requested date as @date" do
        date = Date.create! valid_attributes
        put :update, {:id => date.to_param, :date => valid_attributes}, valid_session
        assigns(:date).should eq(date)
      end

      it "redirects to the date" do
        date = Date.create! valid_attributes
        put :update, {:id => date.to_param, :date => valid_attributes}, valid_session
        response.should redirect_to(date)
      end
    end

    describe "with invalid params" do
      it "assigns the date as @date" do
        date = Date.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Date.any_instance.stub(:save).and_return(false)
        put :update, {:id => date.to_param, :date => {  }}, valid_session
        assigns(:date).should eq(date)
      end

      it "re-renders the 'edit' template" do
        date = Date.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Date.any_instance.stub(:save).and_return(false)
        put :update, {:id => date.to_param, :date => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested date" do
      date = Date.create! valid_attributes
      expect {
        delete :destroy, {:id => date.to_param}, valid_session
      }.to change(Date, :count).by(-1)
    end

    it "redirects to the dates list" do
      date = Date.create! valid_attributes
      delete :destroy, {:id => date.to_param}, valid_session
      response.should redirect_to(dates_url)
    end
  end

end
